## Machine Learning Tutorial 13: KFold Cross Validation

Many times we get in a dilemma of which machine learning model should we use for a given problem. KFold cross validation allows us to evaluate performance of a model by creating K folds of given dataset. This is better then traditional `train_test_split`. In this tutorial, we will cover basics of cross validation and kfold. We will also look into `cross_val_score` function of sklearn library which provides convenient way to run cross validation on a model.

#### Topics covered:
* Cross Validation
* Training Method 1 - Use all available data for training and test on same dataset
* Training Method 2 - Split available dataset into training and test sets
* Training Method 3 - K Fold Cross Validation
* Use handwritten digits dataset for KFold cross validation
* `sklearn.model_selection.KFold`
* `KFold.split` method
* StratifiedKFold
* `cross_val_score`

### K Fold Cross Validation

**Digits dataset from sklearn**

<img src="KFoldCrossVal.png" alt="Classify Using Lines" width="500"/>

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [5]:
digits = load_digits()

In [6]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

**Logistic Regression**

In [7]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

**SVM**

In [8]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.48703703703703705

**Random Forest**

In [9]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

### KFold Cross Validation

**Basic example**

In [10]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Use KFold for our digits example**

In [12]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [15]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [16]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [17]:
scores_rf

[0.9165275459098498, 0.9465776293823038, 0.9198664440734557]

### `cross_val_score` function

**Logistic Regression model performance using `cross_val_score`**

In [18]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

**SVM model performance using `cross_val_score`**

In [19]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

**Random Forest model performance using `cross_val_score`**

In [20]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.92153589, 0.93989983, 0.92654424])

**`cross_val_score` uses Stratified KFold by default**

### Parameter tuning using K Fold Cross Validation

In [21]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
np.average(scores1)

0.8681378026070764

In [22]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

0.9387895716945996

In [23]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

0.9404500310366231

In [24]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores4)

0.9427001862197392

Here we used `cross_val_score` to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.

## Exercise

Use iris flower dataset from `sklearn` library and use `cross_val_score` against following models to measure the performance of each. In the end figure out the model with best performance:

1) Logisitic Regression
2) SVM
3) Decision Tree
4) Random Forest

In [25]:
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [26]:
# Load  the iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [27]:
# Initialize models
logistic_regression = LogisticRegression(max_iter=200)
svm = SVC()
decision_tree = DecisionTreeClassifier()
random_forest = RandomForestClassifier()

In [29]:
# Evaluate models using cross-validation
logistic_regression_scores = cross_val_score(logistic_regression, X, y, cv=5)
svm_scores = cross_val_score(svm, X, y, cv=5)
decision_tree_scores = cross_val_score(decision_tree, X, y, cv=5)
random_forest_scores = cross_val_score(random_forest, X, y, cv=5)

In [30]:
# Calculate the mean scores
logistic_regression_mean = logistic_regression_scores.mean()
svm_mean = svm_scores.mean()
decision_tree_mean = decision_tree_scores.mean()
random_forest_mean = random_forest_scores.mean()

In [31]:
(logistic_regression_mean, svm_mean, decision_tree_mean, random_forest_mean)

(0.9733333333333334, 0.9666666666666666, 0.9666666666666668, 0.96)